pipeline{
    agent any
    // triggers{
    //     cron('*/59 * * * *')
    // }
    // parameters{
    //     string(name:'PARAM_STRING',defaultValue:'input_param',description:'THis is a string')
    // }
    stages{
        stage("Checout"){
            steps{
                withCredentials([usernamePassword(credentialsId:'test_up',
                                                usernameVariable:'USERNAME',
                                                passwordVariable:'PASSWORD')]){
                    echo "$USERNAME $PASSWORD"
                    sh '''
                        echo $USERNAME $PASSWORD
                    '''
                }
                // checkout([$class: 'GitSCM', 
                //         branches: [[name: '*/main']],
                //         userRemoteConfigs: [[url: 'https://github.com/Vithal-Angadi/Jenkins_pipeline.git'
                //         ]]])
            }
        }
    // stages{
    //     stage("Build"){
    //         steps{
    //             sh 'echo "$PARAM_STRING"'
    //         }
    //     }
        // stage("Test"){
            // steps{
                // sh '''
                //    #!/bin/bash
                //    ls -lrt
                //    sleep 10
                // '''
            // }
        //  }
        //  stage("Deploy"){
        //     steps{
        //         sh '''
        //            cd /home/ubuntu
        //            chmod 777 yogu
        //         '''
        //     }
        //  }
    }
}