pipeline{
    agent any
    stages{
        stage("Build"){
            steps{
                sh '''
                    cd /home/ubuntu
                    mkdir vitha
                    chmod 777 vitha
                '''
            }
         }
    }
}