pipeline{
    agent any
    parameters{
        string(name:'PARAM_STRING',defaultValue:'input_param',description:'THis is a string')
    }
    stages{
        stage("Build"){
            steps{
                sh 'echo "$PARAM_STRING"'
            }
        }
        // stage("Test"){
            // steps{
                // sh '''
                //    #!/bin/bash
                //    ls -lrt
                //    sleep 10
                // '''
            // }
        //  }
        //  stage("Deploy"){
        //     steps{
        //         sh '''
        //            cd /home/ubuntu
        //            chmod 777 yogu
        //         '''
        //     }
        //  }
    }
}